pipeline {
  agent any

  environment {
    K8S_NAMESPACE = "securebank"
    HELM_RELEASE = "securebank"
  }

  stages {

    stage('Init') {
      steps {
        script {
          env.GIT_SHA = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
          env.IMAGE_TAG = "${env.BUILD_NUMBER}-${env.GIT_SHA}"
        }
      }
    }

    stage('Build Images') {
      steps {
        sh """
          docker build -t securebank/auth-service:${IMAGE_TAG} apps/auth-service
          docker build -t securebank/account-service:${IMAGE_TAG} apps/account-service
          docker build -t securebank/transaction-service:${IMAGE_TAG} apps/transaction-service
          docker build -t securebank/notification-service:${IMAGE_TAG} apps/notification-service
        """
      }
    }
    
    stage('GitOps Commit') {
      steps {
        withCredentials([usernamePassword(
            credentialsId: 'github-jenkins-creds',
            usernameVariable: 'GIT_USER',
            passwordVariable: 'GIT_TOKEN'
        )]) {
          sh '''
                
            git checkout main
    
            sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" helm/securebank/values.yaml
    
            git add helm/securebank/values.yaml
            git commit -m "chore: deploy build ${IMAGE_TAG}" || echo "No changes to commit"
    
            git push https://${GIT_USER}:${GIT_TOKEN}@github.com/MusaddiqueHussainLabs/securebank_devops.git main
          '''
        }
      }
    }
  }
}
